### ISSUE TITLE
Cannot find package "react-meteor-data" after meteor add react-meteor-data@3.0.0-rc.0

### ISSUE THREAD

**Issue by JanMP** [meteor/react-packages#408]
Trying to run my app with meteor 3.0-rc.4 I get this:
```
> start
> meteor run --exclude-archs web.browser.legacy --settings settings.json

[[[[[ ~/Code/FamZ24 ]]]]]                     

=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
=> Linted your app. No linting errors.        
W20240703-13:18:29.766(2)? (STDERR) packages/core-runtime.js:189
W20240703-13:18:29.772(2)? (STDERR)             throw error;
W20240703-13:18:29.772(2)? (STDERR)             ^
W20240703-13:18:29.772(2)? (STDERR) 
W20240703-13:18:29.772(2)? (STDERR) Error: Cannot find package "react-meteor-data". Try "meteor add react-meteor-data".
W20240703-13:18:29.772(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:704:13)
W20240703-13:18:29.772(2)? (STDERR)     at Module.require (packages/modules-runtime.js:243:14)
W20240703-13:18:29.772(2)? (STDERR)     at Module.mod.require (/Users/jan-michaelpilgenroeder/.meteor/packages/modules/.0.20.1-rc300.4.3usmbe.r45a2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20240703-13:18:29.773(2)? (STDERR)     at Module.moduleLink [as link] (/Users/jan-michaelpilgenroeder/.meteor/packages/modules/.0.20.1-rc300.4.3usmbe.r45a2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:104:22)
W20240703-13:18:29.773(2)? (STDERR)     at module.wrapAsync.self (packages/janmp_sdui/common/roleChecks.coffee:1:1)
W20240703-13:18:29.773(2)? (STDERR)     at Module.wrapAsync (/Users/jan-michaelpilgenroeder/.meteor/packages/modules/.0.20.1-rc300.4.3usmbe.r45a2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20240703-13:18:29.773(2)? (STDERR)     at module (/Users/jan-michaelpilgenroeder/Code/FamZ24/.meteor/local/build/programs/server/packages/janmp_sdui.js:4451:9)
W20240703-13:18:29.773(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20240703-13:18:29.773(2)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20240703-13:18:29.773(2)? (STDERR)     at Module.mod.require (/Users/jan-michaelpilgenroeder/.meteor/packages/modules/.0.20.1-rc300.4.3usmbe.r45a2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
W20240703-13:18:29.773(2)? (STDERR)     at Module.moduleLink [as link] (/Users/jan-michaelpilgenroeder/.meteor/packages/modules/.0.20.1-rc300.4.3usmbe.r45a2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:104:22)
W20240703-13:18:29.773(2)? (STDERR)     at module.wrapAsync.self (packages/janmp_sdui/sdui-server.coffee:1:1)
W20240703-13:18:29.773(2)? (STDERR)     at Module.wrapAsync (/Users/jan-michaelpilgenroeder/.meteor/packages/modules/.0.20.1-rc300.4.3usmbe.r45a2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:251:8)
W20240703-13:18:29.773(2)? (STDERR)     at module (/Users/jan-michaelpilgenroeder/Code/FamZ24/.meteor/local/build/programs/server/packages/janmp_sdui.js:27:9)
W20240703-13:18:29.773(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:335:7)
W20240703-13:18:29.773(2)? (STDERR)     at Module.require (packages/modules-runtime.js:237:14)
W20240703-13:18:29.773(2)? (STDERR) 
W20240703-13:18:29.773(2)? (STDERR) Node.js v20.12.2
```

**Comment by nachocodoner** [comment]
I don't get this issue on my Meteor 3.x app.

![image](https://github.com/meteor/react-packages/assets/2581993/0e7dc143-5e82-49ff-9988-791af3c66815)

![image](https://github.com/meteor/react-packages/assets/2581993/4987dab5-2b93-4b47-926d-5cd90a976900)

Could you try to `meteor reset` or `rm -rf .meteor/local` and retry? Additionally, maybe reinstalling Meteor could help.

Anyway, if you get to have a minimal reproduction repository. It would be good for us to have a closer way to debug the possible issue.

**Comment by nachocodoner** [comment]
If you access to the `.meteor/versions` file, which is the version you see there for `react-meteor-data`?

It should be `react-meteor-data@3.0.0-rc.0`. Just in case it is off this value somehow.

**Comment by JanMP** [comment]
No, when I update from 2.16 to 3.0-rc.8, react meteor-data goes from 2.7.2 to DOWN to 2.0.1 and I get`TypeError: useSubscribe is not a function. (In 'useSubscribe('news')', 'useSubscribe' is undefined)` when it comes up.
Then I `remove`and `add` the package, get to version 3.0.0 and go back to `Error: Cannot find package "react-meteor-data". Try "meteor add react-meteor-data".`above.

**Comment by JanMP** [comment]
I got it to work. Must have been some other dependency causing this problem. I don't know (yet?) which one. I am too exhausted to try and figure that out. I am just glad that problem is gone.
